[project]
name = "sudoku-solver"
version = "0.1.0"
description = "Python code for solving sudoku puzzles."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "termcolor>=2.5.0",
    "z3-solver>=4.13.3.0",
]
